version: "3.8"
services:
  application:
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: dronefeeder
      MYSQL_ROOT_PASSWORD: password
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:


