version: "3.7"
services:
  application:
    build: .
    restart: always
    ports:
      - 8888:8888
    links:
      - mysql:database
  mysql:
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306