spring:
  datasource:
    url: jdbc:mysql://db:3306/dronefeeder?createDatabaseIfNotExist=true
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      platform: mysql
  servlet:
    multipart:
      maxFileSize: 1000000MB
      maxRequestSize: 1000000MB
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        generate-ddl: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        
server:
  port: 8080