version: "3.8"
services:
  application:
    build: .
    restart: on-failure
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{ "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false", "spring.datasource.username" : "$MYSQLDB_USER", "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD", "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect", "spring.jpa.hibernate.ddl-auto" : "update" }'
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    links:
      - mysql:database
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: "mysql:latest"
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${MYSQLDB_LOCAL_PORT}"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
