spring:
  servlet:
    multipart:
      maxFileSize: 1000000MB
      maxRequestSize: 1000000MB
  datasource:
    # url: jdbc:h2:mem:javatpoint
    username: ${MYSQLDB_USER}
    password: ${MYSQLDB_ROOT_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddlAuto: update 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: ${SPRING_LOCAL_PORT}
