spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: password
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
      platform: mysql
  servlet:
    multipart:
      maxFileSize: 1000000MB
      maxRequestSize: 1000000MB
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        generate-ddl: true
        dialect: org.hibernate.dialect.H2Dialect
        
server:
  port: 8080